ifeq ($(PROJECT),yaris_xxl)
EXTRA_CFLAGS += -DYARISXXL
endif
ifeq ($(PROJECT),eclipse)
EXTRA_CFLAGS += -DECLIPSE
endif
obj-$(CONFIG_MTK_SOUND) += AudDrv_Kernel.o AudDrv_Clk.o AudDrv_Afe.o AudDrv_Ana.o
